using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace Prog_poe_part2
{//start of namespace
    public class nlp_manager
    {
        //start of fields
        private Dictionary<string, List<string>> intent_keywords;
        private Dictionary<string, string> intent_responses;
        //end of fields

        //start of constructor
        public nlp_manager()
        {
            //intialize the intent keywords and responses
            load_intents();
        }
        //end of constructor

        //start of method
        private void load_intents()
        {
            intent_keywords = new Dictionary<string, List<string>>
            {
                { "phishing", new List<string> { "phishing", "phish", "fake email", "suspicious email", "scam email", "spam" } },
                { "password", new List<string> { "password", "passwords", "pass", "pin", "credentials", "login" } },
                { "malware", new List<string> { "malware", "virus", "trojan", "spyware", "ransomware", "worm", "infected" } },
                { "vpn", new List<string> { "vpn", "virtual private", "private network", "hide ip", "anonymous" } },
                { "firewall", new List<string> { "firewall", "fire wall", "network protection", "block traffic" } },
                { "2fa", new List<string> { "2fa", "two factor", "two-factor", "authentication", "otp", "verification code" } },
                { "wifi", new List<string> { "wifi", "wi-fi", "public wifi", "wireless", "hotspot" } },
                { "privacy", new List<string> { "privacy", "private", "personal data", "data protection", "gdpr" } },
                { "backup", new List<string> { "backup", "back up", "restore", "recovery", "save data" } },
                { "https", new List<string> { "https", "ssl", "tls", "secure site", "padlock", "certificate" } }
            };

            intent_responses = new Dictionary<string, string>
            {
                { "phishing", "Phishing is when attackers send fake emails or messages to trick you into revealing personal information like passwords or bank details. Always check the sender's email address carefully and never click suspicious links." },
                { "password", "A strong password should be at least 12 characters long and include uppercase letters, lowercase letters, numbers, and special characters. Never reuse passwords across accounts. Consider using a password manager." },
                { "malware", "Malware is malicious software designed to damage or gain unauthorised access to your system. This includes viruses, trojans, spyware, and ransomware. Keep your antivirus updated and avoid downloading files from untrusted sources." },
                { "vpn", "A VPN (Virtual Private Network) encrypts your internet connection and hides your IP address, protecting your privacy especially on public Wi-Fi. It routes your traffic through a secure server." },
                { "firewall", "A firewall monitors and controls incoming and outgoing network traffic based on security rules. It acts as a barrier between your trusted network and untrusted networks like the internet." },
                { "2fa", "Two-Factor Authentication (2FA) adds a second layer of security beyond your password. After entering your password, you verify your identity with a code sent to your phone or generated by an app." },
                { "wifi", "Public Wi-Fi networks are often unsecured. Attackers can intercept your data using a technique called a man-in-the-middle attack. Always use a VPN on public Wi-Fi and avoid accessing sensitive accounts." },
                { "privacy", "Protecting your privacy online means limiting the personal data you share, using strong privacy settings on social media, and understanding how apps use your data. Read privacy policies and avoid oversharing." },
                { "backup", "Regular backups protect your data from ransomware, hardware failure, and accidental deletion. Follow the 3-2-1 rule: 3 copies of data, on 2 different media types, with 1 stored offsite or in the cloud." },
                { "https", "HTTPS means the website uses SSL/TLS encryption to protect data sent between your browser and the server. Always look for HTTPS and the padlock icon before entering sensitive information on any website." }
            };
        }
        //end of method

        //start of method
        public string detect_intent(string input)
        {
            try
            {
                string lower = input.ToLower();
                foreach (var intent in intent_keywords)
                {
                    foreach (string keyword in intent.Value)
                    {
                        if (lower.Contains(keyword))
                            return intent.Key;
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("NLP error: " + ex.Message);
            }
            return null;
        }
        //end of method

        //start of method
        public string get_response(string intent)
        {
            try
            {
                if (intent != null && intent_responses.ContainsKey(intent))
                    return intent_responses[intent];
            }
            catch (Exception ex)
            {
                MessageBox.Show("NLP error: " + ex.Message);
            }
            return null;
        }
        //end of method

    }//end of class
}//end of namespace
